

services:
  postgres:
    image: postgres:15
    container_name: simple-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ketan
      POSTGRES_PASSWORD: ketan
      POSTGRES_DB: simple_server
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
